const state={media:[],destinations:[],playlists:[],streams:[],dashboard:{}};
const $=(q,r=document)=>r.querySelector(q);const $$=(q,r=document)=>[...r.querySelectorAll(q)];
const apiKey=()=>localStorage.getItem('baltigoApiKey')||'';
const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const fmtBytes=n=>{if(!n)return'0 B';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i?1:0)} ${u[i]}`};
const fmtTime=s=>{if(!s)return'—';s=Math.round(s);const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=s%60;return h?`${h}h ${m}m`:`${m}m ${x}s`};
const fmtDate=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
function toast(msg,error=false){const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=msg;$('#toasts').append(el);setTimeout(()=>el.remove(),4000)}
async function api(path,opts={}){const headers={...(opts.headers||{}),'X-API-Key':apiKey()};if(opts.body&&!(opts.body instanceof FormData)){headers['Content-Type']='application/json';opts.body=JSON.stringify(opts.body)}const res=await fetch('/api'+path,{...opts,headers});if(res.status===401){throw new Error('Chave de acesso inválida. Clique em Acesso e informe ADMIN_API_KEY.')}let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data.detail||`Erro ${res.status}`);return data}
function promptKey(){const value=prompt('Informe a ADMIN_API_KEY configurada no servidor:',apiKey());if(value!==null){localStorage.setItem('baltigoApiKey',value.trim());refreshAll()}}
function setView(name){$$('.view').forEach(x=>x.classList.remove('active'));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$('#view-'+name).classList.add('active');$('#page-title').textContent={overview:'Visão geral',streams:'Lives',media:'Mídia',playlists:'Playlists',destinations:'Destinos'}[name];}
function empty(text){return`<div class="empty">${esc(text)}</div>`}
function badge(status){return`<span class="badge ${esc(status)}">${esc(status)}</span>`}
function streamCard(s){const source=s.media_name||s.playlist_name||'—';const action=s.desired_state==='running'?`<button class="btn small danger" onclick="stopStream('${s.id}')">■ Parar</button>`:`<button class="btn small primary" onclick="startStream('${s.id}')">▶ Iniciar</button>`;return`<article class="card"><div class="card-head"><div><h3>${esc(s.name)}</h3><div class="meta">${esc(s.platform||'custom')} · ${esc(s.destination_name)}<br>${esc(source)}</div></div>${badge(s.status)}</div><div class="meta" style="margin-top:14px">Reinícios: ${s.restart_count} · Worker: ${esc(s.worker_id||'—')}<br>${s.scheduled_at?'Agendada: '+fmtDate(s.scheduled_at):s.started_at?'Iniciada: '+fmtDate(s.started_at):'Ainda não iniciada'}</div>${s.last_error?`<div class="meta" style="color:#ff8a9b;margin-top:8px">${esc(s.last_error)}</div>`:''}<div class="card-actions">${action}<button class="btn small" onclick="showLogs('${s.id}')">Logs</button><button class="btn small" onclick="deleteStream('${s.id}')">Excluir</button></div></article>`}
function mediaCard(m){return`<article class="card"><div class="media-icon">▶</div><div class="card-head"><div style="min-width:0"><h3>${esc(m.name)}</h3><div class="meta">${m.width||'?'}×${m.height||'?'} · ${m.fps||'?'} FPS<br>${esc(m.video_codec||'?')} / ${esc(m.audio_codec||'?')} · ${fmtBytes(m.size_bytes)}<br>${fmtTime(m.duration_seconds)}</div></div></div><div class="card-actions"><button class="btn small danger" onclick="deleteMedia('${m.id}')">Excluir</button></div></article>`}
function destinationCard(d){return`<article class="card"><div class="card-head"><div><h3>${esc(d.name)}</h3><div class="meta">${esc(d.platform)}<br>${esc(d.rtmp_url)}</div></div><span class="badge ${d.enabled?'live':'stopped'}">${d.enabled?'ativo':'off'}</span></div><div class="meta" style="margin-top:14px">Stream Key: ${esc(d.stream_key_masked)}</div><div class="card-actions"><button class="btn small danger" onclick="deleteDestination('${d.id}')">Excluir</button></div></article>`}
function playlistCard(p){return`<article class="card"><div class="card-head"><div><h3>${esc(p.name)}</h3><div class="meta">${p.items.length} vídeo(s)</div></div><span class="badge stopped">playlist</span></div><div class="meta" style="margin-top:14px">${p.items.map((x,i)=>`${i+1}. ${esc(x.media.name)}`).join('<br>')}</div><div class="card-actions"><button class="btn small danger" onclick="deletePlaylist('${p.id}')">Excluir</button></div></article>`}
function render(){const d=state.dashboard;$('#stats-grid').innerHTML=[['●',d.live||0,'Ao vivo'],['↻',d.recovering||0,'Recuperando'],['▣',d.media||0,'Vídeos'],['↗',d.destinations||0,'Destinos']].map(([i,n,l])=>`<div class="stat-card"><span>${i} ${l}</span><strong>${n}</strong></div>`).join('');$('#streams-list').innerHTML=state.streams.length?state.streams.map(streamCard).join(''):empty('Nenhuma transmissão criada.');$('#overview-streams').innerHTML=state.streams.length?state.streams.slice(0,3).map(streamCard).join(''):empty('Crie sua primeira transmissão.');$('#media-list').innerHTML=state.media.length?state.media.map(mediaCard).join(''):empty('Sua biblioteca ainda está vazia.');$('#destinations-list').innerHTML=state.destinations.length?state.destinations.map(destinationCard).join(''):empty('Cadastre um destino RTMP.');$('#playlists-list').innerHTML=state.playlists.length?state.playlists.map(playlistCard).join(''):empty('Nenhuma playlist criada.');}
async function refreshAll(){if(!apiKey())return;try{const [dashboard,media,destinations,playlists,streams]=await Promise.all([api('/dashboard'),api('/media'),api('/destinations'),api('/playlists'),api('/streams')]);Object.assign(state,{dashboard,media,destinations,playlists,streams});render()}catch(e){toast(e.message,true)}}
function modal(html){$('#modal').innerHTML=html;$('#modal-backdrop').classList.remove('hidden')}function closeModal(){$('#modal-backdrop').classList.add('hidden')}
function destinationModal(){modal(`<h2>Novo destino</h2><p>Use o Server URL e a Stream Key fornecidos pela plataforma.</p><form id="destination-form" class="form-grid"><div class="field"><label>Nome</label><input name="name" required placeholder="TikTok principal"></div><div class="field"><label>Plataforma</label><select name="platform"><option value="tiktok">TikTok</option><option value="youtube">YouTube</option><option value="twitch">Twitch</option><option value="custom">Custom RTMP</option></select></div><div class="field"><label>Server URL</label><input name="rtmp_url" required placeholder="rtmps://servidor/app"></div><div class="field"><label>Stream Key</label><input name="stream_key" type="password" required autocomplete="off"></div><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary">Salvar destino</button></div></form>`);$('#destination-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('/destinations',{method:'POST',body:Object.fromEntries(f)});closeModal();toast('Destino criado');refreshAll()}catch(err){toast(err.message,true)}}}
function playlistModal(){if(!state.media.length)return toast('Envie pelo menos um vídeo antes.',true);modal(`<h2>Nova playlist</h2><p>A ordem selecionada será mantida na reprodução.</p><form id="playlist-form" class="form-grid"><div class="field"><label>Nome</label><input name="name" required placeholder="Programação principal"></div><div class="field"><label>Vídeos</label><div class="media-checks">${state.media.map(m=>`<label class="media-check"><input type="checkbox" name="media" value="${m.id}"><span>${esc(m.name)} <small class="meta">· ${fmtTime(m.duration_seconds)}</small></span></label>`).join('')}</div></div><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary">Criar playlist</button></div></form>`);$('#playlist-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),ids=f.getAll('media');if(!ids.length)return toast('Selecione ao menos um vídeo.',true);try{await api('/playlists',{method:'POST',body:{name:f.get('name'),media_ids:ids}});closeModal();toast('Playlist criada');refreshAll()}catch(err){toast(err.message,true)}}}
function streamModal(){if(!state.destinations.length)return toast('Cadastre um destino primeiro.',true);if(!state.media.length&&!state.playlists.length)return toast('Envie um vídeo primeiro.',true);const sources=[...state.media.map(m=>`<option value="media:${m.id}">Vídeo · ${esc(m.name)}</option>`),...state.playlists.map(p=>`<option value="playlist:${p.id}">Playlist · ${esc(p.name)}</option>`)];modal(`<h2>Nova transmissão</h2><p>Crie agora ou programe um horário. O worker assume a execução.</p><form id="stream-form" class="form-grid"><div class="field"><label>Nome</label><input name="name" required placeholder="Live principal"></div><div class="field"><label>Destino</label><select name="destination_id">${state.destinations.map(d=>`<option value="${d.id}">${esc(d.name)} · ${esc(d.platform)}</option>`).join('')}</select></div><div class="field"><label>Fonte</label><select name="source">${sources.join('')}</select></div><label class="check-row"><input name="loop" type="checkbox" checked> Repetir continuamente</label><div class="field"><label>Agendar (opcional)</label><input name="scheduled_at" type="datetime-local"></div><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary">Criar live</button></div></form>`);$('#stream-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),[type,id]=String(f.get('source')).split(':');const body={name:f.get('name'),destination_id:f.get('destination_id'),loop:f.get('loop')==='on',media_id:type==='media'?id:null,playlist_id:type==='playlist'?id:null,scheduled_at:f.get('scheduled_at')?new Date(f.get('scheduled_at')).toISOString():null};try{await api('/streams',{method:'POST',body});closeModal();toast(body.scheduled_at?'Live agendada':'Live criada');refreshAll()}catch(err){toast(err.message,true)}}}
async function startStream(id){try{await api(`/streams/${id}/start`,{method:'POST'});toast('Início solicitado');refreshAll()}catch(e){toast(e.message,true)}}async function stopStream(id){try{await api(`/streams/${id}/stop`,{method:'POST'});toast('Parada solicitada');refreshAll()}catch(e){toast(e.message,true)}}async function deleteStream(id){if(!confirm('Excluir esta transmissão?'))return;try{await api(`/streams/${id}`,{method:'DELETE'});toast('Transmissão excluída');refreshAll()}catch(e){toast(e.message,true)}}async function deleteMedia(id){if(!confirm('Excluir este vídeo?'))return;try{await api(`/media/${id}`,{method:'DELETE'});toast('Vídeo excluído');refreshAll()}catch(e){toast(e.message,true)}}async function deleteDestination(id){if(!confirm('Excluir este destino?'))return;try{await api(`/destinations/${id}`,{method:'DELETE'});toast('Destino excluído');refreshAll()}catch(e){toast(e.message,true)}}async function deletePlaylist(id){if(!confirm('Excluir esta playlist?'))return;try{await api(`/playlists/${id}`,{method:'DELETE'});toast('Playlist excluída');refreshAll()}catch(e){toast(e.message,true)}}async function showLogs(id){try{const data=await api(`/streams/${id}/logs?lines=200`);const name=state.streams.find(s=>s.id===id)?.name||'Transmissão';modal(`<h2>Logs · ${esc(name)}</h2><p>Últimas linhas do processo FFmpeg. O destino RTMP é ocultado.</p><code class="log">${esc(data.lines.join('\n')||'Sem logs ainda.')}</code><div class="modal-actions"><button class="btn" onclick="closeModal()">Fechar</button></div>`)}catch(e){toast(e.message,true)}}
$('#media-upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;const fd=new FormData();fd.append('file',file);$('#upload-progress').classList.remove('hidden');try{await api('/media',{method:'POST',body:fd});toast('Vídeo enviado e analisado');refreshAll()}catch(err){toast(err.message,true)}finally{$('#upload-progress').classList.add('hidden');e.target.value=''}};
$$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));$$('[data-open="stream"],#new-stream-btn').forEach(b=>b.onclick=streamModal);$$('[data-open="playlist"]').forEach(b=>b.onclick=playlistModal);$$('[data-open="destination"]').forEach(b=>b.onclick=destinationModal);$('#api-key-btn').onclick=promptKey;$('#modal-backdrop').onclick=e=>{if(e.target===e.currentTarget)closeModal()};window.closeModal=closeModal;Object.assign(window,{startStream,stopStream,deleteStream,deleteMedia,deleteDestination,deletePlaylist,showLogs});
if(!apiKey())setTimeout(promptKey,250);else refreshAll();setInterval(()=>{if(apiKey())refreshAll()},5000);
